### ISSUE TITLE
Issues with WebSocket Connection

### ISSUE THREAD

**Issue by tstraus13** [surrealdb/surrealdb.net#63]
Hello,

I am doing some testing with .Net SurrealDB Client and I came across an issue that I do not have when using the HTTP client. When I do a .Select I get the error/exception "There was a problem with the database: Specify a namespace to use". Even though in the ServiceBuilder area in Program.cs and on the line before the Select I configure it to use a Namespace and Database "test". Whats weird is the same code works perfectly fine connecting over HTTP. It does connect fine over WebSocket but as soon as I do something I get the error. Below is the relevant code snippets. Let me know if you need anything else and thanks for the help.

Program.cs
```
var surrOptions = SurrealDbOptions.Create()
    .WithEndpoint("ws://192.168.122.49:8000/rpc") // Works fine with changing ws to http and removing the /rpc
    .WithNamespace("test")
    .WithDatabase("test")
    .WithUsername("root")
    .WithPassword("root")
    .Build();
builder.Services.AddSurreal(surrOptions);
```

Code/Method Snippet (Dependency Injected)
```
var health = await Surreal.Health();
if (!health)
    await Surreal.Connect();

Surreal.Configure("test", "test");

var counts = await Surreal.Select<CountType>("count_test");

if (counts.FirstOrDefault() != null)
    currentCount = counts.First();
else
    currentCount = new CountType();

private class CountType : Record
{
    public int Count { get; set; }
}
```

**Comment by Odonno** [comment]
Hi Tom.

Indeed, this is a configuration issue on the ws client I encountered recently. I am currently working on a fix.

In the meantime, you can use the HTTP client if that's ok for you.
Thank you for reporting the issue.

**Comment by Odonno** [comment]
Hi @tstraus13 

This is now fixed in v0.3.1

**Comment by LoKolbasz** [comment]
I am still experiencing this issue with v0.3.1.

For me the error occurs milliseconds after starting the client so I don't think a ping can resolve it.

**Comment by Odonno** [comment]
Ah, right. I did not see the example code provided. I can see why it failed. The `Health` method was supposed to be used when the ws client is already in use/connected.

I will fix it. Until then, you can remove or comment the `Health` call, it should work perfectly.

**Comment by Odonno** [comment]
Fixed in v0.4.0.

**Comment by tstraus13** [comment]
Thanks for fixing. I hope to use use Surreal one day for a project. Just need the idea :)
